Rename global CMake vars

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -16,12 +16,14 @@ defaults:
 env:
   VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
 
+  # TODO: Create macOS CMake scripts so can use `TARGET_BUNDLE_DIR` and not env vars here?
+
   # NOTE: Can't use env vars inside of env vars (Inception).
-  GHW_BIN_NAME: 'EkoScape'
-  GHW_PKG_NAME: 'EkoScape-macos-universal'
-  GHW_PKG_DIR: 'build/_CPack_Packages/Darwin/Bundle/EkoScape-macos-universal'
-  GHW_BUNDLE_NAME: 'EkoScape.app'
-  GHW_BUNDLE_DIR: 'build/_CPack_Packages/Darwin/Bundle/EkoScape-macos-universal/EkoScape.app'
+  EKO_EXE_NAME: 'EkoScape'
+  EKO_PKG_NAME: 'EkoScape-macos-universal'
+  EKO_PKG_DIR: 'build/_CPack_Packages/Darwin/Bundle/EkoScape-macos-universal'
+  EKO_BUNDLE_NAME: 'EkoScape.app'
+  EKO_BUNDLE_DIR: 'build/_CPack_Packages/Darwin/Bundle/EkoScape-macos-universal/EkoScape.app'
 
 jobs:
   build:
@@ -70,14 +72,14 @@ jobs:
 
       - name: Rename ${{ matrix.arch }}
         run: |
-          mv -v 'bin/Release/${{ env.GHW_BIN_NAME }}' \
-                'bin/Release/${{ env.GHW_BIN_NAME }}-${{ matrix.arch }}'
+          mv -v 'bin/Release/${{ env.EKO_EXE_NAME }}' \
+                'bin/Release/${{ env.EKO_EXE_NAME }}-${{ matrix.arch }}'
 
       - name: Upload ${{ matrix.arch }}
         uses: actions/upload-artifact@v4
         with:
           name: "macos-bin-${{ matrix.arch }}"
-          path: "bin/Release/${{ env.GHW_BIN_NAME }}-*"
+          path: "bin/Release/${{ env.EKO_EXE_NAME }}-*"
           if-no-files-found: error
           compression-level: 6
           overwrite: true
@@ -115,7 +117,7 @@ jobs:
           -DVCPKG_CRT_LINKAGE=static
           -DVCPKG_LIBRARY_LINKAGE=static
           -DVCPKG_BUILD_TYPE=release
-          -DEKO_PKG_SUFFIX='-universal'
+          -DEKO_PKG_NAME_SUFFIX='-universal'
           -DEKO_PKG_MACOS_USE_BUILD_UNI_DIR=ON
 
       - name: Download bins
@@ -128,51 +130,51 @@ jobs:
       - name: Build uni
         run: |
           set -x
-          chmod +x 'build_uni_temp/${{ env.GHW_BIN_NAME }}'*
-          lipo -info 'build_uni_temp/${{ env.GHW_BIN_NAME }}'*
+          chmod +x 'build_uni_temp/${{ env.EKO_EXE_NAME }}'*
+          lipo -info 'build_uni_temp/${{ env.EKO_EXE_NAME }}'*
 
           mkdir -v build_uni
-          lipo -create 'build_uni_temp/${{ env.GHW_BIN_NAME }}'* \
-               -output 'build_uni/${{ env.GHW_BIN_NAME }}'
-          lipo -info 'build_uni/${{ env.GHW_BIN_NAME }}'
+          lipo -create 'build_uni_temp/${{ env.EKO_EXE_NAME }}'* \
+               -output 'build_uni/${{ env.EKO_EXE_NAME }}'
+          lipo -info 'build_uni/${{ env.EKO_EXE_NAME }}'
           set +x
 
       - name: Package up
         run: cpack -C Release --config build/CPackConfig.cmake -B build --verbose
 
       - name: Debug bundle
-        run: ls -alR '${{ env.GHW_PKG_DIR }}'
+        run: ls -alR '${{ env.EKO_PKG_DIR }}'
 
       - name: Verify bundle
         run: cmake --build --preset default --config Release --target check_macos_bundle
 
       - name: Verify Info.plist
-        run: plutil -lint '${{ env.GHW_BUNDLE_DIR }}/Contents/Info.plist'
+        run: plutil -lint '${{ env.EKO_BUNDLE_DIR }}/Contents/Info.plist'
 
       - name: Verify bundle deps
-        run: otool -L '${{ env.GHW_BUNDLE_DIR }}/Contents/MacOS/${{ env.GHW_BIN_NAME }}'
+        run: otool -L '${{ env.EKO_BUNDLE_DIR }}/Contents/MacOS/${{ env.EKO_EXE_NAME }}'
 
       - name: Test running bundle
         run: |
           set -x
-          xattr -r -d com.apple.quarantine '${{ env.GHW_BUNDLE_DIR }}'
-          file '${{ env.GHW_BUNDLE_DIR }}'
-          file '${{ env.GHW_BUNDLE_DIR }}/Contents/MacOS/${{ env.GHW_BIN_NAME }}'
+          xattr -r -d com.apple.quarantine '${{ env.EKO_BUNDLE_DIR }}'
+          file '${{ env.EKO_BUNDLE_DIR }}'
+          file '${{ env.EKO_BUNDLE_DIR }}/Contents/MacOS/${{ env.EKO_EXE_NAME }}'
 
-          '${{ env.GHW_BUNDLE_DIR }}/Contents/MacOS/${{ env.GHW_BIN_NAME }}' --version
-          open '${{ env.GHW_BUNDLE_DIR }}' --args --version || echo '[ERROR] Failed to open app bundle.'
+          '${{ env.EKO_BUNDLE_DIR }}/Contents/MacOS/${{ env.EKO_EXE_NAME }}' --version
+          open '${{ env.EKO_BUNDLE_DIR }}' --args --version || echo '[ERROR] Failed to open app bundle.'
           set +x
 
       - name: Compress bundle
         run: |
           set -x
-          tar -czf 'build/${{ env.GHW_PKG_NAME }}.tar.gz' \
-              -C '${{ env.GHW_PKG_DIR }}' \
-              '${{ env.GHW_BUNDLE_NAME }}' \
+          tar -czf 'build/${{ env.EKO_PKG_NAME }}.tar.gz' \
+              -C '${{ env.EKO_PKG_DIR }}' \
+              '${{ env.EKO_BUNDLE_NAME }}' \
               '.itch.toml'
           cd build
-          shasum -a 256 '${{ env.GHW_PKG_NAME }}.tar.gz' \
-                 > '${{ env.GHW_PKG_NAME }}.tar.gz.sha256'
+          shasum -a 256 '${{ env.EKO_PKG_NAME }}.tar.gz' \
+                 > '${{ env.EKO_PKG_NAME }}.tar.gz.sha256'
           cd -
           set +x
 
